server:
  port: 8082

spring:
  application:
    name: blocker-service

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: false

management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: metrics, prometheus