server:
  port: 8090

spring:
  config:
    import: "kubernetes:"
  application:
    name: gateway-api
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/realms/master

resilience4j.circuitbreaker:
  instances:
    exampleCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5