logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8090

spring:
  config:
    import: "kubernetes:"
  application:
    name: gateway-api
  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true

resilience4j.circuitbreaker:
  instances:
    exampleCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5