server:
  port: 8090

spring:
  application:
    name: gateway-api
  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500                # Порт Consul-агента (по умолчанию 8500)
      config:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8070/realms/master

resilience4j.circuitbreaker:
  instances:
    exampleCircuitBreaker:
      registerHealthIndicator: true
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 10s
      permittedNumberOfCallsInHalfOpenState: 3
      minimumNumberOfCalls: 5