services:
  gateway-api:
    build:
      context: ./gateway-api
      dockerfile: Dockerfile
    depends_on:
      - keycloak
    environment:
      - 'SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/master'

  keycloak:
    image: 'quay.io/keycloak/keycloak:26.2.5'
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

  bank-ui:
    build:
      context: ./bank-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - gateway-api
    environment:
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI=http://keycloak:8080/realms/master/protocol/openid-connect/token'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWk_SET_URI=http://keycloak:8080/realms/master/protocol/openid-connect/certs'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI=http://keycloak:8080/realms/master/protocol/openid-connect/userinfo'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI=http://keycloak:8080/realms/master/protocol/openid-connect/auth'