server:
  port: 8087

spring:
  application:
    name: transfer-service            # Имя сервиса в реестре Consul

  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500                # Порт Consul-агента (по умолчанию 8500)
      config:
        enabled: false