logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8087

spring:
  config:
    import: "kubernetes:"
  application:
    name: transfer-service

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true