server:
  port: 8087

spring:
  config:
    import: "kubernetes:"
  application:
    name: transfer-service            # Имя сервиса в реестре Consul

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true