apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{- if ne $key "database_url" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}