spring:
  config:
    import: "kubernetes:"
  application:
    name: bank-ui

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: sub
            token-uri: http://localhost:8070/realms/master/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8070/realms/master/protocol/openid-connect/certs
            user-info-uri: http://localhost:8070/realms/master/protocol/openid-connect/userinfo
            authorization-uri: http://localhost:8070/realms/master/protocol/openid-connect/auth
        registration:
          gateway-api:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: gateway-api
            client-secret: qG809wzghjzF9tjT3Da5cqe4dBkTYOe1
            clientAuthenticationMethod: client_secret_post
            scope: profile

bank-services:
  gateway-api: http://gateway-api