logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

spring:
  config:
    import: "kubernetes:"
  application:
    name: bank-ui

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: sub
        registration:
          gateway-api:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: gateway-api
            client-secret: qG809wzghjzF9tjT3Da5cqe4dBkTYOe1
            clientAuthenticationMethod: client_secret_post
            scope: profile


management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: metrics, prometheus