spring:
  config:
    import: "consul:"
  application:
    name: bank-ui            # Имя сервиса в реестре Consul

  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500                # Порт Consul-агента (по умолчанию 8500)
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config          # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию

  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: sub
            token-uri: http://localhost:8070/realms/master/protocol/openid-connect/token
            jwk-set-uri: http://localhost:8070/realms/master/protocol/openid-connect/certs
            user-info-uri: http://localhost:8070/realms/master/protocol/openid-connect/userinfo
            authorization-uri: http://localhost:8070/realms/master/protocol/openid-connect/auth
        registration:
          gateway-api:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: gateway-api
            client-secret: qG809wzghjzF9tjT3Da5cqe4dBkTYOe1
            clientAuthenticationMethod: client_secret_post
            scope: profile

bank-services:
  gateway-api: http://gateway-api