apiVersion: v1
kind: ConfigMap
metadata:
  name: cash-service
data:
  application.properties: |
    accounts_service_url={{ include "bank.accountsServiceURL" . }}
    blocker_service_url={{ include "bank.blockerServiceURL" . }}
    notification_service_url={{ include "bank.notificationServiceURL" . }}