server:
  port: 8083

spring:
  config:
    import: "kubernetes:"
  application:
    name: cash-service            # Имя сервиса в реестре Consul

  cloud:
    kubernetes:
      config:
        namespace: bank-ns
        sources:
          - name: exchange-application