logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG

server:
  port: 8083

spring:
  config:
    import: "kubernetes:"
  application:
    name: cash-service

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true

  kafka:
    bootstrap-servers: 'localhost:9092'
    producer:
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      client-id: cash-service
      fail-fast: true

bank_app_notifications_topic: "bank-app.notifications"

management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: metrics, prometheus