server:
  port: 8083

spring:
  config:
    import: "consul:"
  application:
    name: cash-service            # Имя сервиса в реестре Consul

  cloud:
    consul:
      host: localhost           # Адрес Consul-агента (по умолчанию localhost)
      port: 8500                # Порт Consul-агента (по умолчанию 8500)
      config:
        enabled: true            # Включаем Consul Config для внешней конфигурации
        prefix: config          # Префикс в KV-хранилище Consul (по умолчанию "config")
        defaultContext: application  # Контекст по умолчанию