server:
  port: 8081

spring:
  application:
    name: accounts-service

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/practicum
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus