server:
  port: 8081

spring:
  application:
    name: accounts-service

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/practicum
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect