apiVersion: v2
name: bank-app
description: An umbrella Helm chart to deploy the whole app
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: accounts
    version: "0.1.0"
    repository: "file://charts/accounts"
  - name: bank-ui
    version: "0.1.0"
    repository: "file://charts/bank-ui"
  - name: blocker
    version: "0.1.0"
    repository: "file://charts/blocker"
  - name: cash
    version: "0.1.0"
    repository: "file://charts/cash"
  - name: exchange
    version: "0.1.0"
    repository: "file://charts/exchange"
  - name: exchange-generator
    version: "0.1.0"
    repository: "file://charts/exchange-generator"
  - name: gateway
    version: "0.1.0"
    repository: "file://charts/gateway"
  - name: notifications
    version: "0.1.0"
    repository: "file://charts/notifications"
  - name: transfer
    version: "0.1.0"
    repository: "file://charts/transfer"
  - name: keycloak
    version: "24.8.1"
    repository: "https://charts.bitnami.com/bitnami"