global:
  domain: myapp.local # Example domain for ingress

##########################################################################################

accounts-db:
  enabled: true
  auth:
    database: practicum
    username: accounts_user
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi

##########################################################################################

bank-keycloak:
  auth:
    adminUser: admin
    adminPassword: admin

  postgresql:
    enabled: true
    auth:
      username: bn_keycloak
      password: bn_keycloak
      database: bitnami_keycloak

  extraEnvVars:
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"

  extraVolumes:
    - name: realm-config
      configMap:
        name: keycloak-realm-config

  extraVolumeMounts:
    - name: realm-config
      mountPath: /opt/bitnami/keycloak/data/import
      readOnly: true

##########################################################################################

bank-kafka:
  replicaCount: 3

  kraft:
    enabled: true

  auth:
    enabled: false

  listeners:
    client:
      protocol: 'PLAINTEXT'
    controller:
      protocol: 'PLAINTEXT'

  externalAccess:
    enabled: false

  persistence:
    enabled: false

  provisioning:
    enabled: true
    topics:
      - name: bank-app.rates
        partitions: 1
        replicationFactor: 3
      - name: bank-app.notifications
        partitions: 1
        replicationFactor: 3
      - name: bank-app.logs
        partitions: 1
        replicationFactor: 3

  controller:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

  broker:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

##########################################################################################

bank-zipkin:
  enabled: true
  service:
    type: ClusterIP
    port: 9411

  cassandra:
    enabled: false
    tls:
      enabled: false
      autoGenerated:
        enabled: false

  storageType: memory

  persistence:
    enabled: false

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

##########################################################################################