bankUi:
  servicePort: 8080
  env:
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: "http://keycloak:8080/realms/master/protocol/openid-connect/token"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWk_SET_URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI: "http://keycloak:8080/realms/master/protocol/openid-connect/userinfo"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI: "http://keycloak:8080/realms/master/protocol/openid-connect/auth"

gateway:
  env:
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8080/realms/master"

keycloak:
  adminUser: admin
  adminPassword: admin
  realmImportPath: ./keycloak/

accounts:
  env:
    SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgres:5432/compose-postgres
    SPRING_DATASOURCE_USERNAME: compose-postgres
    SPRING_DATASOURCE_PASSWORD: compose-postgres