global:
  domain: myapp.local # Example domain for ingress
  accountsServiceURL: "http://exchange-service:8084"
  blockerServiceURL: "http://exchange-service:8084"
  exchangeServiceURL: "http://exchange-service.myapp.local"
  notificationServiceURL: "http://exchange-service:8084"
  bankUIURL: "http://exchange-service:8084"
  gatewayURL: "http://exchange-service:8084"
  cashServiceURL: "http://exchange-service:8084"
  transferServiceURL: "http://exchange-service:8084"

accounts-db:
  enabled: true
  auth:
    database: practicum
    username: accounts_user
    password: "changeM3Customer!" # Example: Not recommended for production
  primary:
    persistence:
      enabled: true
      size: 1Gi

bank-keycloak:
  command:
    - "/opt/bitnami/keycloak/bin/kc.sh"
    - "start-dev"
  extraEnvVars:
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      value: admin
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      value: admin
    - name: KEYCLOAK_EXTRA_ARGS
      value: "--import-realm"
  extraVolumes:
    - name: realm-config
      configMap:
        name: keycloak-realm-config
  extraVolumeMounts:
    - name: realm-config
      mountPath: /opt/bitnami/keycloak/data/import
      readOnly: true