apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker-service.fullname" . }}
  labels:
    {{- include "blocker-service.labels" . | nindent 4 }}
data:
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://bank-app-bank-zipkin:9411/api/v2/spans