replicaCount: 1

image:
  repository: blocker-service # Default to local image name
  pullPolicy: IfNotPresent      # Default to IfNotPresent
  tag: "0.0.1-SNAPSHOT"         # Default tag matching build

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: LoadBalancer
  port: 8082

ingress:
  enabled: true
  className: "nginx"
  annotations: { }
  hosts:
    - host: blocker-service.myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

resources: { }

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: [ ]

volumeMounts: [ ]

nodeSelector: { }

tolerations: [ ]

affinity: { }
