pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = credentials('DOCKER_REGISTRY')
        DB_PASSWORD     = credentials('DB_PASSWORD')
        GITHUB_USERNAME = credentials('GITHUB_USERNAME')
        DB_NAME         = 'mydb'
        DB_USER         = 'myuser'
        IMAGE_TAG       = "${env.BUILD_NUMBER}"
    }

     stages {
            stage('Gradle Build') {
                steps {
                    echo 'Running Gradle clean buildAll...'
                    sh './gradlew clean buildAll'
                }
            }

            stage('Build Docker Images') {
                steps {
                    echo 'Running build_images.sh...'
                    sh './build_images.sh'
                }
            }

            stage('Helm Dependency Build') {
                steps {
                    echo 'Running helm dependency build...'
                    sh 'helm dependency build ./bank-app'
                }
            }

            stage('Helm Install') {
                steps {
                    echo 'Installing bank-app via Helm...'
                    sh 'helm install bank-app ./bank-app'
                }
            }
        }

        post {
            failure {
                echo 'Pipeline failed!'
            }
            success {
                echo 'Pipeline completed successfully!'
            }
        }
}