apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: common-pod-reader-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "umbrella-chart.commonServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: common-pod-reader
  apiGroup: rbac.authorization.k8s.io
