apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scrape-config
  namespace: monitoring
data:
  prometheus.yaml: |
    scrape_configs:
      - job_name: 'my-custom-service'
        static_configs:
          - targets: ['my-service:8080']
