server:
  port: 8085

spring:
  config:
    import: "kubernetes:"
  application:
    name: exchange-generator-service            # Имя сервиса в реестре Consul

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true