server:
  port: 8099

spring:
  config:
    import: "kubernetes:"
  application:
    name: exchange-generator-service

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true

  kafka:
    bootstrap-servers: 'localhost:9092'
    admin:
      client-id: exchange-generator-service
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1

bank_app_rates_topic: "bank-app.rates"