replicaCount: 1

image:
  repository: notifications-service # Default to local image name
  pullPolicy: IfNotPresent      # Default to IfNotPresent
  tag: "0.0.1-SNAPSHOT"         # Default tag matching build

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: common-service-account

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

service:
  type: LoadBalancer
  port: 8086

ingress:
  enabled: true
  className: "nginx"
  annotations: { }
  hosts:
    - host: notifications-service.bank-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

resources: { }

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 60
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: [ ]

volumeMounts: [ ]

nodeSelector: { }

tolerations: [ ]

affinity: { }
