apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-api
data:
  application.properties: |
    accounts_service_url={{ include "bank.accountsServiceURL" . }}
    cash_service_url={{ include "bank.cashServiceURL" . }}
    transfer_service_url={{ include "bank.transferServiceURL" . }}
    exchange_service_url={{ include "bank.exchangeServiceURL" . }}
    spring.security.oauth2.resourceserver.jwt.issuer-uri=http://bank-app-bank-keycloak/realms/master