server:
  port: 8086

spring:
  config:
    import: "kubernetes:"
  application:
    name: notifications-service

  cloud:
    kubernetes:
      discovery:
        enabled: true
      config:
        enabled: true