replicaCount: 1

image:
  repository: accounts-service # Default to local image name
  pullPolicy: IfNotPresent      # Default to IfNotPresent
  tag: "0.0.1-SNAPSHOT"         # Default tag matching build

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: common-service-account

podAnnotations: { }

podSecurityContext: { }

securityContext: { }

service:
  type: LoadBalancer
  port: 8081

ingress:
  enabled: true
  className: "nginx"
  annotations: { }
  hosts:
    - host: accounts-service.bank-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: [ ]

resources: { }

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: { }

tolerations: [ ]

affinity: { }

config:
  database_url: "jdbc:postgresql://{{ .Release.Name }}-accounts-db:5432/practicum"
  database_username: "accounts_user"
  database_password: "changeM3Customer!" # Example: Not recommended for production